### ISSUE TITLE
"add an image to the entry first" - windows chrome

### ISSUE THREAD

**Issue by johnjayhopley** [contentful/apps#108]
![image (3)](https://user-images.githubusercontent.com/39731841/87945325-7d0c0180-ca98-11ea-81ae-e8983dde475c.png)
Currently getting the following error but only when using windows chrome 

"add an image to the entry first"

checked other browsers using windows and osx and it seems fine. Seems like it's only windows chrome i am getting this.

**Comment by davidfateh** [comment]
Hi @johnjayhopley 

Thanks for the information about this problem. Would you mind submitting this to Contentful support so we can have someone take a look at your specific case?

**Comment by davidfateh** [comment]
Will handle in support.

**Comment by ragmn** [comment]
any update ont his one?
