### ISSUE TITLE
netlify app doesn't load

### ISSUE THREAD

**Issue by awkale** [contentful/apps#109]
I had the app installed and it wasn't always showing up in the sidebar so I uninstalled. When trying to reinstall it, it won't load.

<img width="1454" alt="image" src="https://user-images.githubusercontent.com/744487/88094408-7eedc780-cb61-11ea-850d-bbc79f2e7396.png">

**Comment by davidfateh** [comment]
Hey @awkale,

I was not able to repro this on a few different spaces of mind. Would you mind checking out the console and seeing if any requests to `https://netlify.ctfapps.net/` are coming through or being blocked?

**Comment by awkale** [comment]
I finally figured it out. My duck duck go extension was blocking it. https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg

Thanks for the help!
