### ISSUE TITLE
`experiment.key` is undefined error

### ISSUE THREAD

**Issue by pnarielwala-tc** [contentful/apps#112]
### Hello 👋 

My company is exploring adding the Opimizely app to our Contentful space and while testing, I'm running into an issue where selecting an experiment does not populate the "Variations" section for the user to choose from.

![Image 2020-07-30 at 4 22 41 PM](https://user-images.githubusercontent.com/37671065/88970818-0bdf0200-d281-11ea-83f2-cbf3b3560012.png)

After doing a little digging, it seems like the Optimizely endpoint that is being used to get all the experiments doesn't return experiments with object key `key`; not sure if the REST api endpoint has been updated or not, but is it possible to fix this by not using that key value?

re:https://github.com/contentful/apps/blob/ce9bbeb412cd5b7da843f1f25b150a6932f38e20/apps/optimizely/src/EditorPage/subcomponents/experiment-section.js#L57

Thank you!

**Comment by davidfateh** [comment]
Hi @pnarielwala-tc 

I've spent some time running the Optimizely app on my own space with some of my experiments and was unable to reproduce the problem. That being said, I'm wondering if the experiment you are choosing is compatible with the app. The app only works with [Optimizely Full Stack ](https://www.optimizely.com/platform/full-stack/) projects. Are you using some other project type?

For more information about our Optimizely app, please see our [documentation](https://www.contentful.com/developers/docs/extensibility/apps/optimizely/).

Thanks,
David

**Comment by pnarielwala-tc** [comment]
Hello @davidfateh,

You're right, we only have Web projects - my bad, clearly didn't read the requirements section 😔 lol.

Thanks,
Parth
