### ISSUE TITLE
Deprecate examples?

### ISSUE THREAD

**Issue by kamsar** [contentful/apps#128]
There are some app samples here: https://github.com/contentful/apps/tree/master/examples

But these seem a lot less helpful than what `create-contentful-app` makes (i.e. cca demonstrates all the extension points, includes test skeletons, etc). Is it potentially worth marking these examples deprecated and sending folks to create-contentful-app instead?

**Comment by bsgreenb** [comment]
I think they're both useful, e.g. seeing shopify example app, but would like to see the examples kept up to date.

**Comment by davidfateh** [comment]
Hey all! The examples directory is indeed a bit old. It was the precursor to all the documentation and tooling we currently have. 

#### Thoughts on the Hello World app:
I believe the Hello World app is fairly basic and may not contribute much value to the learning experience. I will do a deeper dive to determine if it is actually detrimental to the learning experience. By detrimental, I mean "Does the example actually teach bad practices that are no longer valid today or does it simply add to the confusion?"

#### Thoughts on the Page Location app:
This app I see as being very valuable. Our page location can be considered a bit unique in the sense that it allows the developer to control the URL/navigation of the main app to a certain degree. This leaves open the possibility for deep linking into an app via a custom path in the URL. Our example uses react-router to showcase this functionality and could be seen as a template of sorts. However, I believe this app could use some touching-up to make sure that it is in a good shape.

Let me know what you think.

**Comment by davidfateh** [comment]
Hi and again thanks for the feedback. As an update, I've removed the hello world app but have kept the page location app for reasons I described above. I'm going to close this issue now.
