### ISSUE TITLE
Cloudinary Image Metadata Update

### ISSUE THREAD

**Issue by hamwithglasses** [contentful/apps#134]
I'm pretty sure this is more of a limitation and not an issue, but once I've selected an image and added it in Contentful, if I go into Cloudinary and want to update Meta Data this information is not pushed back to Contentful in any way.

I'm assuming in a situation like this I have to build/setup my own hook for when Cloudinary images change if I want it to reflect in Contentful, or simply repick the "new" image in Contentful for this new info to show up.

Just looking for confirmation on if this is the intended behavior.

**Comment by jelz** [comment]
This is expected behavior: we use object data at the moment of insertion to Contentful and don't keep it in sync with Cloudinary data.
