### ISSUE TITLE
[SHOPIFY] This app uses the (unsupported) 2019-10 version of the graphql api

### ISSUE THREAD

**Issue by code-by-gijs** [contentful/apps#1357]
**Describe the bug**
The Shopify contentful app is using an unsupported api version. There is no option to select another version as it is hardcoded in the app. For now this will keep on working. But in 2023-01 the base64 hased object id's are no longer supported: https://shopify.dev/api/examples/object-ids. This Shopify app will no longer work with the latest Shopify version in 2023-01. Would it be possible to select what version of the api you want to use in the shopify app configuration?

**Comment by shikaan** [comment]
Hello @code-by-gijs and thanks for the report!

We have filed an issue in our backlog to take care of this issue and you can expect a resolution soon, although I am currently unable to provide a certain resolution date. Should you have any problems, you can check the related issue [here](https://github.com/contentful/apps/issues/1206). I am closing this issue to keep the information in one place and we'll update the other thread as soon as we have news.

Thanks again for the heads-up and have a great day ahead,
Manuel
