### ISSUE TITLE
[commercetools] app uses unsupported api

### ISSUE THREAD

**Issue by carlokok** [contentful/apps#1410]
**Describe the bug**
When listing categories in the contentful commercetools app it uses categorySearch. However categorySearch is not a supported api:

{{{"data":null,"errors":[{"message":"Cannot query field 'categorySearch' on type 'Query'. Did you mean 'category' or 'categories'? (line 2, column 3):\n categorySearch(fulltext:
{text: $searchTerm, locale: $locale}

) {\n ^","locations":[
{"line":2,"column":3}

]}]}}}

**To Reproduce**
1. Setup a commercetools app
2. Hookup categories
3. Try and search for a category
4. See error in console, nothing shows

**Expected behavior**
To use the proper apis for this.

{{{"data":null,"errors":[{"message":"Cannot query field 'categorySearch' on type 'Query'. Did you mean 'category' or 'categories'? (line 2, column 3):\n categorySearch(fulltext:
{text: $searchTerm, locale: $locale}

) {\n ^","locations":[
{"line":2,"column":3}

]}]}}}

**Comment by andipaetzold** [comment]
Hey @carlokok ,

we rebuild the commercetools app a couple of weeks ago and you shouldn't run into this issue anymore. Feel free to reopen this issue if you're still running into issues.
