### ISSUE TITLE
MUX app adds a value when there is no video that causes problem if the field is required.

### ISSUE THREAD

**Issue by atasoyh** [contentful/apps#1415]
**Describe the bug**
 there is a problem on MUX App, when the video is required and there is no video; It doesn't give an error. As it put a value inside the field.
 
**To Reproduce**
1. Make any video field required.
2. Add and remove the video
3. you can publish the content without a video

**Expected behavior**
Field should give an error when there is no video and should block publishing.

**Screenshots**

It shows the value when we delete the video;
<img width="763" alt="Screenshot 2022-06-30 at 11 13 25" src="https://user-images.githubusercontent.com/1092496/176718173-655f6fae-f7f8-48cb-9057-9931728784a8.png">

**Comment by blairliikala** [comment]
This should be fixed in the next release.
