### ISSUE TITLE
request : apps/shopify - add variant name in product select

### ISSUE THREAD

**Issue by lexstefan** [contentful/apps#142]
Hello,

I've been testing the shopify app in contentful and I have noticed the products don't have a variant name displayed even tho' the graphQL query has it. Would be nice enough to fix this? Most shops have variants to products, and the product selector has the same product listed 2-3 times when in fact there are 2 to 3 different variants to that product. A regular user would find it difficult to select the correct product variant.

```
{
    nodes (ids: [${queryIds}]) {
      id,
      ...on ProductVariant {
        sku,
        image {
          src: originalSrc
        },
        title,
        product {
          id,
          title
        }
      }
    }
  }
```

Thank you!

**Comment by cmwall** [comment]
Having the same issue. It seems like the "SKU" for the product is not actually an SKU or a variant name, but instead a UUID from Shopify.  
<img width="349" alt="image" src="https://user-images.githubusercontent.com/13528491/95521283-2f1be100-0997-11eb-94d6-392286dd703a.png">

**Comment by lexstefan** [comment]
I was checking out the apps repository. And apparently the shopify app is using another app to output in the confluent ui. I would have 100% done it and PR it but i haven't had a chance to read up on how to test it. I'll probably have to dedicate some time to this. Couse' this issue is 2 weeks old and nobody said anything about it.

**Comment by jeanniesarah** [comment]
Any luck?

**Comment by Jwhiles** [comment]
Hey @lexstefan if you're able to work on a PR for this feature that would be great. Otherwise, if it's a feature you'd like to see added could you submit your feature request through the support link [on this page](https://www.contentful.com/marketplace/app/shopify/)? Cheers!

**Comment by OriginalEXE** [comment]
Hey everyone,

Just to let you know that thew latest version of the Shopify app now fixes this issue, variant name (or sku if available) should now show up instead of the id. Hopefully this makes it more useable.

I have also added support for picking products and collections (and not just product variants), you can configure the behavior in the app config page.
