### ISSUE TITLE
[commercetools] hardcoded (european) api url in commercetools client not respecting url specified in app config

### ISSUE THREAD

**Issue by zeindev** [contentful/apps#1425]
https://github.com/contentful/apps/blob/bc92c7b1cc06a49f9bf0f9cff4bce881761d020e/apps/commercetools/src/api/client.ts#L9

App appears to be calling the european api endpoint, ignoring the api url specified in config.
We are unable to fetch products from commercetools' US api endpoint.

**Comment by colomolo** [comment]
@zeindev thanks for opening this issue
