### ISSUE TITLE
Cloudinary thumbnails are broken when Strict Transformations are enabled

### ISSUE THREAD

**Issue by electriccode** [contentful/apps#144]
This is happening because the Cloudinary thumbnail URL is in wrong format
https://res.cloudinary.com/ID/image/upload/q_auto:good/w_150,h_100,c_fill/v1/path-to-asset

When strict transformations are enabled then this URL can never be exposed using named transformations due to following reasons
1. Transformations have transformations sorted alphabetically, so while `c_fill,h_100,w_150` works, `w_150,h_100,c_fill` won't.
2. Transformation can't be named as `q_auto:good/w_150,h_100,c_fill` becuase `/` are not allowed.

The fix is the correct the order of transformations in thumbnail by sorting them alphabetically.

**Comment by jelz** [comment]
Fixed in #146
