### ISSUE TITLE
Request: apps/netlify - Change Language on the "Open preview" button

### ISSUE THREAD

**Issue by moop-moop** [contentful/apps#150]
Please change the language on the button.
Use of the term preview is not really correct. The button goes to the site's URLs nothing more that I can tell. It doesn't use the Preview content API for example like might be set up using Contentful's built in preview features.

Which makes it very confusing to have 2 preview buttons in the sidebar. One being a real preview the other, a link to the site.

I suggest:
- Open Site
- View Deployed Site
- View Site
- Open Deployed Site

 An option to hide the button altogether would also be an excellent change.

**Comment by Jwhiles** [comment]
Hey @moop-moop - sorry for the slow reply.

As this is a feature request, could you please it through our [support channel here](https://www.contentful.com/support/)
