### ISSUE TITLE
Request: apps/netlify - Read only view for certain roles

### ISSUE THREAD

**Issue by moop-moop** [contentful/apps#151]
Feature request for the Netlify app.

It would be very useful to be able to allowed permission based access to the app in the sidebar. So that the ability to trigger any deployment is driven by role.
Case:
Anyone without permission to trigger a built could see the active deploying statuses in a Read Only form. And those with permission get the fully functional app.

**Comment by Jwhiles** [comment]
Hey @moop-moop - sorry for the slow reply. 

As this is a feature request, could you please it through our support channel [here](https://www.contentful.com/support/)
