### ISSUE TITLE
Request: Netlify branch deploys

### ISSUE THREAD

**Issue by davidhousedev** [contentful/apps#159]
We are using a branch deploy in Netlify to deploy our site to a `preview` subdomain, where the only difference from prod is that the preview subdomain uses the Contentful preview API, rather than the CDN.

Ideally, we would like to be able to use the Contentful Netlify app to point content editors to the `preview` subdomain rather than the production domain (where content will only exist when published).

There are a few changes that would significantly improve the usefulness of this app for us, if the app could be specific to a branch deploy on a Contentful site:
  * The "Deploy site" button would build that branch deploy and not build the production deploy
  * Clicking "Open preview" would open up that branch deploy, if a subdomain deploy exists for that branch
  * The "building status" view and the "Last built n minutes go..." text would be specific to the branch deploy

**Comment by Jwhiles** [comment]
Hi @davidhousedev - sorry for the slow response.

As this is a feature request, could you please submit it through our [support system here](https://www.contentful.com/support/), this will allow our team to properly review and prioritise your proposed changes.
