### ISSUE TITLE
[commercetools] Product preview is limited to 20 products

### ISSUE THREAD

**Issue by img-alc** [contentful/apps#1592]
**Issue description**
Adding more than 20 products to a field leads to "Product missing" message in products preview

**Steps to reproduce**
1. Create a new entry (content type must have a field with commerce tools app installed for products widget)
2. Add more than 20 products to the field connected to commerce tools
3. Save
4. Only 20 products are properly shown, while exceeding products show the message mentioned before

**Screenshot**
![image](https://user-images.githubusercontent.com/16797534/183671953-fb27be90-c3e5-4fb4-8d62-e49199d4ed34.png)

**Expected behavior**
I expected all selected products to show correctly in the preview, the error message is misleading. The products do exist and should render (name & image).

**Root cause**
Commerce tools api response is limited to 20 entries. You have to provide the offset in order to fetch remaining results. Example of a response:
![image](https://user-images.githubusercontent.com/16797534/183673874-518d19b6-34cf-41aa-bc12-95db31c95e2f.png)

The logic to fetch the products preview is not considering the number of results, always returning at most 20 entries ([link](https://github.com/contentful/apps/blob/425a0ccace45ba724d1485e32d93de6074acc375/apps/commercetools/src/api/products.ts)).

```
export async function fetchProductPreviews(
  skus: string[],
  config: ConfigurationParameters
): Promise<Product[]> {
  if (skus.length === 0) {
    return [];
  }

  const client = createClient(config);
  const response = await client
    .productProjections()
    .search()
    .get({
      queryArgs: {
        'filter.query': [`variants.sku:${skus.map((sku) => `"${sku}"`).join(',')}`],
      },
    })
    .execute();

  if (response.statusCode === 200) {
    const products = response.body.results.map(productTransformer(config));
    const foundSKUs = products.map((product: Product) => product.sku);
    const missingProducts = skus
      .filter((sku) => !foundSKUs.includes(sku))
      .map((sku) => ({
        sku,
        image: '',
        id: '',
        name: '',
        isMissing: true,
      }));
    return [...products, ...missingProducts];
  }
  throw new Error(`Request failed with status ${response.statusCode}`);
}
```

**Comment by colomolo** [comment]
@img-alc Thanks for opening the issue. We now fetching max possible amount of products. Should be enough for most cases.
