### ISSUE TITLE
[CommerceTools] No search feature for selecting categories

### ISSUE THREAD

**Issue by RickProductLeague** [contentful/apps#1638]
As a content editor, when opening the product selector, products can be searched using a search input field within the product selector. However, for categories there is no search feature. As you can imagine, selecting the right category when there are many to choose from is not very practical (see image).

Would it be possible to also add the search feature to the category selector widget?

![image](https://user-images.githubusercontent.com/94116709/185621038-453ec2b4-65a0-434c-97c5-b17fbd97638f.png)

**Comment by andipaetzold** [comment]
Hey,

unfortunately this is not possible. We used to have a search for categories as well, but that API was disabled by commercetools. There is currently no replacement for that API.
