### ISSUE TITLE
"Add an image to the entry first" - On localization Content having multiple locale images

### ISSUE THREAD

**Issue by ragmn** [contentful/apps#1932]
Works fine with an English locale.  When I try to set the focal point on 2nd locale, it throws an error. 
![image](https://user-images.githubusercontent.com/10610334/199725214-20a7f02c-70bc-4c94-92a5-6524dad00cba.png)

**Comment by kdamball** [comment]
Hi @ragmn, could you provide more context please? Are you using the contentful app or did you fork the app and using your own implementation? Are you also using the built in content model the app creates or did you manually assign the app to an existing content model?

I managed to reproduce it but for multi locale images and similarly multi locale focal point fields. Fix linked above ☝🏾

**Comment by ragmn** [comment]
Hi @kdamball,  Thank you very much! it's sorted now :)
