### ISSUE TITLE
ecommerce-app-base: Selected SKUs can't be saved if pager was used

### ISSUE THREAD

**Issue by JohnnySk** [contentful/apps#1938]
**Describe the bug**
Was used ecommerce-app-base template, all needed functions were made and setup was performed using **setup** function from @contentful/ecommerce-app-base package. Also was used **renderSkuPicker** function with pagination, using this setup I'm not able to save selected products (SKUs) from any page except first. Maybe there is some issue with data related to selected products in state?

**To Reproduce**
1. setup project using @contentful/ecommerce-app-base
2. prepare callback functions for setup function from @contentful/ecommerce-app-base.
3. use renderSkuPicker function from @contentful/ecommerce-app-base package and implement pagination with products result response
4. Try to save any product from any page except first. You will not be able to see preview of saved SKU (Product)

**Expected behavior**
Save any Product from response from needed platform (Shopware, Magento, etc...) even using pagination inside **renderSkuPicker** function.

**Comment by kdamball** [comment]
Hi @JohnnySk Thanks for the report. I will report back with after investigation with either a fix PR or further explanation

**Comment by kdamball** [comment]
Hi @JohnnySk, I debugged our pagination against our implementation of [commercetools app](https://github.com/contentful/apps/blob/master/apps/commercetools/src/api/products.ts#L62-L97). I am able to select products from other pages besides the first one. How are you implementing `fetchProductPreviews` and `fetchProducts` props passed into `renderSkuPicker`? It might helpful to see how we do it in the same [commercetools app](https://github.com/contentful/apps/blob/master/apps/commercetools/src/dialog.ts#L46-L54).

**Comment by JohnnySk** [comment]
Hi @kdamball , there is my implementation example: https://github.com/JohnnySk/contentful-magento-product-field/tree/magento_client
so, in details: **fetchProductPreviews** implemented here: https://github.com/JohnnySk/contentful-magento-product-field/blob/magento_client/src/index.js#L45
**fetchProducts** here: https://github.com/JohnnySk/contentful-magento-product-field/blob/magento_client/src/index.js#L77

**Comment by JohnnySk** [comment]
Hi @kdamball , did you had a chance to check my version of implementation, is it somewhere a missed code part or something like wrong implementation of fetchProducts, renderSkuPicker functions ? Thanks

**Comment by JohnnySk** [comment]
@andipaetzold , agree with you regarding code review and debugging, just asked because it was mentioned in conversation above. Thanks a lot, I will find a solution after debugging the way of realisation in [commerstools app](https://github.com/contentful/apps/blob/master/apps/commercetools/src/dialog.ts#L46-L54)
