### ISSUE TITLE
Configuring app logo or icon 

### ISSUE THREAD

**Issue by danielstocks** [contentful/apps#229]
Hi,

This is more a question/feature request than an issue, but:

I've spent some time going through the Contentful App framework documentation and the [SDK reference](https://www.contentful.com/developers/docs/extensibility/app-framework/sdk/) but I can't find anything around configuring an Icon/logo for the app. 

Any pointers?

Thanks in advance

**Comment by danielstocks** [comment]
For context, this is what I'm talking about:

![Screenshot 2021-05-05 at 16 07 10](https://user-images.githubusercontent.com/52788/117154532-3afc4400-adbc-11eb-96a6-f7ef22981d90.png)

Follow up question, is there also a way to add a "description" for the app as can be seen for the GraphQL playground app.

**Comment by Jwhiles** [comment]
Hey @danielstocks - sorry for the slow response to this issue.

Currently the descriptions and icons that you've mentioned are only available for apps that appear on our Marketplace, but not for private apps. We may enable these for private apps in the future though.
