### ISSUE TITLE
Increase Cloudinary App MAX_FILES_UPPER_LIMIT

### ISSUE THREAD

**Issue by jroco-cloudinary** [contentful/apps#2300]
Hi Team, 

We got an inquiry if it is possible to increase the limit for MAX_FILES_UPPER_LIMIT. Currently it is set to 25.

Best Regards,
John

**Comment by mgoudy91** [comment]
Hey @jroco-cloudinary, apologize for the late response, we just changed our support process for GitHub issues.

 I'll check with the team and see why this decision was made.

**Comment by ryunsong-contentful** [comment]
Hey @jroco-cloudinary - Thought I'd update you here and just let you know that we just increased the limit to 1000 now!

**Comment by ryunsong-contentful** [comment]
Closing as the request has now been fulfilled
