### ISSUE TITLE
The upload script missing from some of the example apps

### ISSUE THREAD

**Issue by raimohanska** [contentful/apps#2351]
**Describe the bug**

In custom-validation example (and possibly others) the upload script is missing.

**Expected behavior**

I'd expect the create-contentful-app to work as described in your documentation, regardless of the selected example.

**Comment by raimohanska** [comment]
In fact the setup is outdated in other ways as well for the custom-validation app. It results into a bundle that has an absolute path to the JS bundle and does not work. I copied one of the newer vite-based example builds for my use case and I'm good for now. Just hope that you can fix this for your next customer :)

**Comment by loweisz** [comment]
Hey @raimohanska 

Thanks for pointing that out 🙇 , I just opened a PR that should include it in the example where it wasn't present before

**Comment by raimohanska** [comment]
Great! Thanks for the quick reply. 

It makes sense to check the other examples as well. At a glance they seemed to be based on varied build tools and I don’t know which of them actually work.
