### ISSUE TITLE
Color Picker Widget Id for Migrations

### ISSUE THREAD

**Issue by stephenlautier** [contentful/apps#2886]
Whats the Color picker `widgetId` to be used for migrations?

Tried with `widgetNamespace: "app`" and widgetId `colorPicker` or `color-picker` but no luck

```ts
type.changeFieldControl(vars.fieldId, "app", "colorPicker", {
	helpText: vars.helpText || "",
});
```

Unfortunately in contentful JSON preview of the entity it doesnt show it, and i cant seem to find in anywhere in source or doc

**Comment by andipaetzold** [comment]
👋 

The namespace is correct. The id is `4Vy3oAINwRgnxakoTz06tG`.

You could've found it by requesting the `editor_interface` resource of your content type. Yes, that's not very intuitive... I'll forward your problem internally, so we can make this easier.
