### ISSUE TITLE
Cloudinary widget cannot insert images into Contentful

### ISSUE THREAD

**Issue by isobar-nmutis-mesa** [contentful/apps#311]
**Describe the bug**
 
The Cloudinary widget is no longer able to insert/associate files into Contentful.

**To Reproduce**

1. Log into Contentful and navigate your Space content
2. Create or go to an existing entry of a content type that has a field assigned to be handled by the Cloudinary app
2. Click on "Select or upload file on Cloudinary" to open the Cloudinary widget
3. Select a single file within the Cloudinary media library
4. Click on "Insert"
5. Nothing happens; an error is displayed in the developer console (please see screenshot)

**Expected behavior**

The widget should get dismissed and the Cloudinary image should be inserted/previewed in the corresponding Contentful entry field.

**Screenshots**

![Screen Shot 2021-07-05 at 2 52 29 pm](https://user-images.githubusercontent.com/1841164/124420579-0cdab680-dda3-11eb-8ff6-1239962bfe10.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.4, Windows 10 Professional (Version 10.0.19043 Build 19043)
 - Browser and version: Chrome 91.0.4472.114 (macOS), Chrome 91.0.4472.124 (Windows 10 Professional)

**Additional context**

This appeared to have been working at least until sometime Friday 2 July and was only detected today.

**Comment by andipaetzold** [comment]
Hey @isobar-nmutis-mesa ,

thanks for the detailed error report!
We just deployed a new version of the app that should resolve your issue.

**Comment by isobar-nmutis-mesa** [comment]
Thanks so much - really appreciate it!

**Comment by isobar-nmutis-mesa** [comment]
Apologies, it seems that this has been mostly resolved; it continues to occur in a different view within the widget. I've added details below but can raise a separate issue if needed. (they're nearly identical to the original)

**Describe the bug**
 
The Cloudinary widget is no longer able to insert/associate files into Contentful using the widget's **detail** view.

**To Reproduce**

Steps to reproduce the behavior:

1. Log into Contentful and navigate your Space content
2. Create or go to an existing entry of a content type that has a field assigned to be handled by the Cloudinary app
2. Click on "Select or upload file on Cloudinary" to open the Cloudinary widget
3. **Double click** into a single file within the Cloudinary media library to access the detail view
4. Click on "Insert"
5. Nothing happens; an error is displayed in the developer console (please see screenshot)

**Expected behavior**

The widget should get dismissed and the Cloudinary image should be inserted/previewed in the corresponding Contentful entry field.

**Screenshots**

![Screen Shot 2021-07-06 at 11 06 39 am](https://user-images.githubusercontent.com/1841164/124528167-dbb5c100-de4a-11eb-9f67-90f56437eb48.png)

**Desktop (please complete the following information):**

- OS: macOS 11.4, Windows 10 Professional (Version 10.0.19043 Build 19043)
- Browser and version: Chrome 91.0.4472.114 (macOS), Chrome 91.0.4472.124 (Windows 10 Professional)

**Comment by andipaetzold** [comment]
Yesterday's fix unfortunately only resolved the issue when selecting and inserting an asset via the checkbox. 

Thanks for the bug report, again! We identified the same issue yesterday already and are in contact with Cloudinary to solve this issue. Unfortunately, we cannot fix the bug by updating our app but have to wait for Cloudinary to release a hotfix. Until then, the workaround is to use the checkbox to select and insert assets instead of double-clicking an asset.

I will post an update here as soon as a hotfix has been rolled out.

**Comment by andipaetzold** [comment]
Good news! Cloudinary released the fix and both insert buttons are working again. 🎉 

You might need to refresh the page or clear your cache to get the latest update. If the error persists, please reach out again.
