### ISSUE TITLE
[Optimizely App] Buged experiment/variations selection.

### ISSUE THREAD

**Issue by piotrgrundas** [contentful/apps#3491]
**Describe the bug**
Using Optimizely app I am unable to create variations after selecting Experiment in the Variation Container.

**To Reproduce**
1. Follow the Contentful Optimizely [tutorial](https://www.contentful.com/help/optimizely-app/) and follow to [4 step](https://www.contentful.com/help/optimizely-app/#4-usage).
2. Add a Variation Container to the page and open its configuration.
3. Select the appropriate experiment.
4. An error is present in the console and no Variations are populated.

**Expected behavior**
Variations are populated without errors.

**Screenshots**
![image](https://github.com/contentful/apps/assets/5078402/4f215442-4e5e-4231-a1c5-7c1f124d59c4)
![image](https://github.com/contentful/apps/assets/5078402/f674d9ff-93e7-43c3-a717-348a0a882356)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: Version 113.0.5672.92 (Official Build) (arm64)

**Comment by matthew-gordon** [comment]
Hey @piotrgrundas, thank you for reaching out about this.

We suspect that it may be an issue with the project type selected, currently the Optimizely app is not compatible with Optimizely `Full Stack 2.0`, only  `Full Stack Legacy ` is supported and may be causing the issues you are experiencing.

Would you mind trying to create a Full Stack Legacy Project and seeing if your variants propagate as expected?

**Comment by piotrgrundas** [comment]
Hey @matthew-gordon
I don't see an option to do so in Optimizely, am I missing something? 
Might it be so, because that's the default type now?

**Comment by matthew-gordon** [comment]
@piotrgrundas No worries, from your account settings you can select `Create New Project`:

<img width="1122" alt="Screenshot 2023-05-17 at 9 30 00 AM" src="https://github.com/contentful/apps/assets/22120469/98c15d7a-1ec1-4165-8eab-1c4ca00fcd46">

From there you should see an options screen, select `Create Feature Experimentation Project`:

<img width="841" alt="Screenshot 2023-05-17 at 9 37 29 AM" src="https://github.com/contentful/apps/assets/22120469/9c1064a7-4b94-4444-a269-77c7f3e73be6">

After navigating there, you should see a checkbox that reads `Use Legacy Experience`:

<img width="807" alt="Screenshot 2023-05-17 at 9 29 25 AM" src="https://github.com/contentful/apps/assets/22120469/6d42513a-52ba-4e48-851b-864b6cc846b6">

Let me know if this works for you! I believe you are correct, that is the default now and currently there are no immediate plans to support `Full Stack 2.0`.

**Comment by whitelisab** [comment]
Hi @piotrgrundas. There are no immediate plans to support Full Stack 2.0 in our integration. I would encourage you to ask Optimizely about building a Contentful App which supports their newest features.
