### ISSUE TITLE
Cloudinary/dam-app-base - Allow user to edit already selected assets

### ISSUE THREAD

**Issue by kcfilip** [contentful/apps#3969]
Hello, 

I have a question regarding to extending functionality of `Field` component in `dam-app-base`
We have a feature requested which would allow editors to edit metadata about the already selected image (cloudinary):

Currently there is no way to open/edit already selected image, we can only sort them:

<img width="550" alt="Screenshot 2023-07-03 at 12 40 30" src="https://github.com/contentful/apps/assets/80714178/9c4b7bf9-8fcf-405c-b2f4-3f82be7b4133">

---

### Possible solutions:

1. Allow editors to click on the image and open the dialog, and pre-select the asset (not sure if feasable?)

<img width="600" alt="Screenshot 2023-07-03 at 12 41 22" src="https://github.com/contentful/apps/assets/80714178/69f0676d-09ea-4001-a13e-cdfbbd89398d">

---

2. Expose file name in the `Field `, which would allow editors to easily search the asset by filename, and edit the metadata and related information. 

<img width="600" alt="Screenshot 2023-07-03 at 12 41 41" src="https://github.com/contentful/apps/assets/80714178/3a6ea8f3-0b79-487c-b50f-aab904ccc03c">

Looking forward to your feedback!
https://github.com/the-infatuation, we have an experience in building custom app for contentful. We would be open to contributing to this project if this feature makes sense to you.

**Comment by whitelisab** [comment]
Hi @kcfilip! Thank you for reaching out. I talked to our product team and they appreciate the feedback. We are open to you contributing this feature to this project. As an FYI, the Cloudinary app uses this Media Library Widget for the dialog: https://cloudinary.com/documentation/media_library_widget.

Let us know if you have any questions, and thank you again for your feedback.

**Comment by whitelisab** [comment]
Hey @kcfilip 👋 Just wanted to provide an update here. We have actually prioritized working on some improvements to the Cloudinary app where we will be exposing more details about the selected asset (similar to solution #2 that you proposed above). I'm closing this ticket for now, but feel free to reach out again if you have more questions.
