### ISSUE TITLE
Cloudinary integration: Metadata not coming through

### ISSUE THREAD

**Issue by loremipson** [contentful/apps#54]
I don't know how to run or test an app like this on my end, or if it's even possible, so I can't confirm that this actually will fix it:

I believe [this line](https://github.com/contentful/apps/blob/master/apps/cloudinary/src/index.js#L22) needs to be `image_metadata` instead of `metadata`

**Comment by davidfateh** [comment]
Hey @loremipson, thanks for the information. We will take a look into this.

**Comment by davidfateh** [comment]
@loremipson after inspecting the data we get back from Cloudinary in our integration it looks like `metadata` is the correct key name. However, I do see that if you were to add custom metadata fields to an asset via the UI, then they would show up in `context`. Is that what you are actually looking for?

If so I believe my #59 PR should help expose those values.

**Comment by loremipson** [comment]
Yes, I'm sure that custom metadata fields will be useful to have at some point, but I am wanting to pull the default `title` and `description` metadata that Cloudinary has to use as `title` and `alt` properties.

If `context` also has those, then this should be perfect!

**Comment by davidfateh** [comment]
Sounds good. I've opened the PR for review. Once approved, it will go live. However, since we save the Cloudinary data into Contentful, you will need to reselect the images you wish to get the metadata for and republish those entries.
