### ISSUE TITLE
sap-commerce-cloud

### ISSUE THREAD

**Issue by FilipeAPV** [contentful/apps#5599]
**Describe the bug**

1. The total number of pages is not being updated in `Dialog.tsx` state.
The problem seems to come from the method `updateTotalPages` that is not using the function parameter "totalPages":
```
updateTotalPages = (totalPages: number) => {
    // this.setState({ totalPages: this.state.totalPages }); -> bug
    this.setState({ totalPages: totalPages }); 
  };
```

2. Two bugs in the following code also from `Dialog.tsx`:

```
  nextPageButtonEvent = () => {
    this.setState({ page: this.state.page - 1 });
    this.load();
  };

  prevPageButtonEvent = () => {
    this.setState({ page: this.state.page - 1 });
    this.load();
  };
```
- `nextPageButtonEvent ` should be + 1, to retrieve the next page
- setState is async, so this.load() is going to be called with the non-updated value.

Maybe something like this would be the solution:
```
nextPageButtonEvent = () => {
  this.setState({ page: this.state.page + 1 }, () => {
    this.load();
  });
};
```

**To Reproduce**
1. Install and configure connector
2. Open connector dialog
3. In the first bug, the pagination btn's will not be shown. In the second one, you'll be working with the previous value of "page".

**Comment by rusticpenguin** [comment]
Thank you so much for triaging this Filipe! I'll be working to get these fixes in tomorrow!

**Comment by lilbitner** [comment]
Hi @FilipeAPV, thank you for raising this bug! We have pushed a fix and it should be resolved now. Please feel free to open another Github issue if you find issues on your end with the resolution.
