### ISSUE TITLE
AI Content Generator: Unexpected token error when using GPT-4

### ISSUE THREAD

**Issue by joakimgunst** [contentful/apps#6285]
I'm using the AI Content Generator app with an OpenAI API paid account API key and the GPT-4 model configured. When using clicking Generate in the app, the app UI shows the following error message:

> The stream was interrupted. Please try again.

In the console I see the following error:

```
index-bf8d8e8b.js:21 SyntaxError: Unexpected token 'd', "data: {"id"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Kt (index-bf8d8e8b.js:1:8674)
    at Array.reduce (<anonymous>)
    at Ke.parseStream (index-bf8d8e8b.js:1:9725)
    at async S (index-bf8d8e8b.js:21:6282)
    at async onGenerate (index-bf8d8e8b.js:21:13806)
```

When configuring the app top use the GPT-3.5 everything works fine. Our OpenAI API plan includes access to GPT-4, so that shouldn't be the issue.

I wonder if there could be some issue in the [`streamToParsedText`](https://github.com/contentful/apps/blob/064c910b2a62ed680ca1792a20aa47325c940a27/apps/ai-content-generator/src/utils/aiApi/aiHelpers.ts#L52) function?

**Comment by joakimgunst** [comment]
Here's the place in the minified code that the error occurs at:

<img width="376" alt="Screenshot 2024-02-06 at 12 59 16" src="https://github.com/contentful/apps/assets/15349412/53ada0ea-3a07-40e9-b5ab-f00b76222bb2">

**Comment by jsdalton** [comment]
Thanks for the issue report @joakimgunst .

This was great timing -- we just encountered the issue ourselves and shipped a fix for it this morning.

Give it at try, should be working now. If it's not we can reopen the issue.

**Comment by joakimgunst** [comment]
Yes, it is working. Thanks!
