### ISSUE TITLE
Mux app: video preview using signed URL stopped working

### ISSUE THREAD

**Issue by sgarg7** [contentful/apps#6339]
**Describe the bug**
Contentful previews of MUX assets using signed URLs stopped working and give the error message: `No signing key to create a playback token. Preview playback may not work. Try toggling the global signing key settings.`

**To Reproduce**
1. Install MUX app with signed URLs, notice it mentions a signing key will be used.
2. Go to a type that uses the MUX asset video, try to preview video in Contentful. 

**Expected behavior**
Video should be able to be previewed

**Screenshots**
![image](https://github.com/contentful/apps/assets/1569480/48a48410-fe8e-4330-b266-415ca96af6de)
![image](https://github.com/contentful/apps/assets/1569480/5ca28f2e-9f40-416d-9de4-5edaa6808057)

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser: Microsoft edge
 - Version 121.0.2277.83 (Official build) (arm64)

**Additional context**

**Comment by rusticpenguin** [comment]
Thanks for pointing this out Shishir! We are actively working on a fix for this. In the interim, we have rolled back the app to the last known working build.

**Comment by sgarg7** [comment]
I believe this is working again. Thank you, this can be closed.
