### ISSUE TITLE
Shopify App - Pulls variance but not products

### ISSUE THREAD

**Issue by Burnsy** [contentful/apps#64]
Hello, for my use case we wanted to host all the extra information for the products on contentful and match them with the Shopify ids. But while working on it I noticed that the products that can be selected through contentful are the variations of the products and not the overarching product.

Any advice in how to get the overarching product of the variants through contentful? 

Thank you.

**Comment by giotiskl** [comment]
@Burnsy the Shopify app deals with product variants as you mentioned and the persisted value is always the ID of the selected variant.

However, once you have this ID you can query Shopify for the product. If you scroll to the FAQ section of the app here: https://www.contentful.com/developers/docs/extensibility/apps/shopify/

The answer to the question `How can I query the Shopify Storefront API for the products whose IDs I saved in my Contentful entries?` gives an example of a GraphQL Query that would allow you to get the overarching product product id, plus any other pieces of data needed for the product.

**Comment by avcohen** [comment]
Is there a more complete example of how this is implemented?

Am I correct to assume one can structure a query where all `productVariantIDs` are retrieved from Contentful and passed into the second part of the query as noted in the reply? I'm still a bit new to GraphQL and wondering how I might combine all this into a single query. 

If not, I take it this has to be broken up into two queries?

Thanks

**Comment by OriginalEXE** [comment]
Just to note - The Shopify app now supports choosing between a product, product variant, or collection picking. You can configure this on a per-field basis in the app config.

**Comment by marttihyvonen** [comment]
Id which Contentful Shopify Add-on returns is pretty weird, I can't get this kind of ID out from Shopify's own Storefront API, so ID is pretty useless for me. 

ID Contenful Shopify App is returning: 

<img width="710" alt="image" src="https://github.com/contentful/apps/assets/4487596/06c82f7f-e1ca-4454-ac2a-ee108f1a51cc">


IDs I get from Shopify Storefront API are in format:

`gid://shopify/Product/9552832528700`


Any ideas?

Thanks a lot in advance :)

**Comment by marttihyvonen** [comment]
I just figured this out, IDs Contentful API is returning are Base64 encoded Shopify IDs.
