### ISSUE TITLE
[nextjs] An object literal cannot have multiple properties with the same name

### ISSUE THREAD

**Issue by seanValtech** [contentful/apps#6904]
**Describe the bug**
The template creates an object called ComponentLocationSettings which has multiple entries with the same name

**To Reproduce**
1. Create a new app with `yarn create contentful-app my-first-next-app --yarn --example nextjs`
2. Go to file `pages/index.tsx`
3. See error as two entries have the name `locations.LOCATION_PAGE`

![image](https://github.com/contentful/apps/assets/50106382/e1254fb7-8729-4f79-a396-da7bc37fe656)

**Expected behavior**
Each entry should have a unique name

**Comment by whitelisab** [comment]
Hi @seanValtech! Thanks for reporting this issue in the nextjs example. I just merged in a fix, so I am closing this issue 😄
