### ISSUE TITLE
Allow Apps to function as "Page extension"

### ISSUE THREAD

**Issue by DaniRey** [contentful/apps#77]
My current understanding is that [Page extensions](https://www.contentful.com/developers/docs/extensibility/ui-extensions/locations/) can currently only be built with Extensions, but not with Apps.

Can you add this capability to the App Framework?

**Comment by davidfateh** [comment]
Hey @DaniRey I'm happy to say that I've been building out that functionality. Right now we are wrapping up the development phase and will be entering the QA phase soon. I'll keep you posted!

**Comment by davidfateh** [comment]
Hi @DaniRey,

We've just released the page location for apps. This means you can have your app show up in the main navigation bar of Contentful as well as have a location for your app all to itself!

See our [changelog](https://www.contentful.com/developers/changelog/#full-page-apps-can-now-hook-into-the-main-navigation) for more resources.

**Comment by DaniRey** [comment]
Thank you @davidfateh. We already started using it and it works great. Great improvement over the extensions, that it received a separate navigation item. 

So far we only miss, that we can not use the `slideIn` option in the Navigator and that the back button, after navigating to an Entry, does not go back to the app.

We will raise separate tickets for those limitations.

**Comment by davidfateh** [comment]
@DaniRey That's awesome to hear! You make some good points and we've noted them for future releases :)
